# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_gui(object):
    def setupUi(self, gui):
        if gui.objectName():
            gui.setObjectName(u"gui")
        gui.resize(480, 270)
        gui.setMinimumSize(QSize(480, 270))
        gui.setMaximumSize(QSize(480, 270))
        self.centralwidget = QWidget(gui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.save_label = QLabel(self.centralwidget)
        self.save_label.setObjectName(u"save_label")
        self.save_label.setGeometry(QRect(69, 135, 161, 31))
        self.save_label.setMinimumSize(QSize(150, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_label.setFont(font)
        self.save_label.setAutoFillBackground(True)
        self.save_label.setAlignment(Qt.AlignCenter)
        self.open_label = QLabel(self.centralwidget)
        self.open_label.setObjectName(u"open_label")
        self.open_label.setGeometry(QRect(69, 93, 161, 31))
        self.open_label.setMinimumSize(QSize(150, 25))
        self.open_label.setFont(font)
        self.open_label.setAutoFillBackground(True)
        self.open_label.setAlignment(Qt.AlignCenter)
        self.open_format = QComboBox(self.centralwidget)
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.addItem("")
        self.open_format.setObjectName(u"open_format")
        self.open_format.setGeometry(QRect(250, 95, 151, 31))
        font1 = QFont()
        font1.setBold(True)
        font1.setItalic(False)
        font1.setWeight(75)
        self.open_format.setFont(font1)
        self.open_format.setAutoFillBackground(True)
        self.save_format = QComboBox(self.centralwidget)
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.addItem("")
        self.save_format.setObjectName(u"save_format")
        self.save_format.setGeometry(QRect(250, 135, 151, 31))
        self.save_format.setFont(font1)
        self.save_format.setAutoFillBackground(True)
        self.title_label = QLabel(self.centralwidget)
        self.title_label.setObjectName(u"title_label")
        self.title_label.setGeometry(QRect(40, 10, 400, 41))
        self.title_label.setMinimumSize(QSize(400, 0))
        self.title_label.setBaseSize(QSize(100, 0))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        font2.setWeight(75)
        self.title_label.setFont(font2)
        self.title_label.setAutoFillBackground(True)
        self.title_label.setAlignment(Qt.AlignCenter)
        self.name_label = QLabel(self.centralwidget)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(170, 50, 150, 25))
        self.name_label.setMinimumSize(QSize(150, 25))
        font3 = QFont()
        font3.setPointSize(10)
        self.name_label.setFont(font3)
        self.name_label.setAutoFillBackground(True)
        self.name_label.setAlignment(Qt.AlignCenter)
        self.unlock_bottom = QPushButton(self.centralwidget)
        self.unlock_bottom.setObjectName(u"unlock_bottom")
        self.unlock_bottom.setGeometry(QRect(350, 206, 101, 41))
        font4 = QFont()
        font4.setPointSize(15)
        font4.setBold(False)
        font4.setWeight(50)
        self.unlock_bottom.setFont(font4)
        self.unlock_bottom.setAutoFillBackground(True)
        self.lock_bottom = QPushButton(self.centralwidget)
        self.lock_bottom.setObjectName(u"lock_bottom")
        self.lock_bottom.setGeometry(QRect(30, 206, 101, 41))
        self.lock_bottom.setFont(font4)
        self.lock_bottom.setAutoFillBackground(True)
        gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(gui)

        QMetaObject.connectSlotsByName(gui)
    # setupUi

    def retranslateUi(self, gui):
        gui.setWindowTitle(QCoreApplication.translate("gui", u"\u795e\u9f99\u52a0\u5bc6 v1.4", None))
        self.save_label.setText(QCoreApplication.translate("gui", u"\u4fdd\u5b58\u6587\u4ef6\u683c\u5f0f", None))
        self.open_label.setText(QCoreApplication.translate("gui", u"\u6253\u5f00\u6587\u4ef6\u683c\u5f0f", None))
        self.open_format.setItemText(0, QCoreApplication.translate("gui", u"utf-8", None))
        self.open_format.setItemText(1, QCoreApplication.translate("gui", u"utf-8-sig", None))
        self.open_format.setItemText(2, QCoreApplication.translate("gui", u"gb2312", None))
        self.open_format.setItemText(3, QCoreApplication.translate("gui", u"gbk", None))
        self.open_format.setItemText(4, QCoreApplication.translate("gui", u"gb18030", None))
        self.open_format.setItemText(5, QCoreApplication.translate("gui", u"big5", None))
        self.open_format.setItemText(6, QCoreApplication.translate("gui", u"koi8-r", None))
        self.open_format.setItemText(7, QCoreApplication.translate("gui", u"cp932", None))
        self.open_format.setItemText(8, QCoreApplication.translate("gui", u"windows-1250", None))
        self.open_format.setItemText(9, QCoreApplication.translate("gui", u"windows-1251", None))
        self.open_format.setItemText(10, QCoreApplication.translate("gui", u"windows-1252", None))
        self.open_format.setItemText(11, QCoreApplication.translate("gui", u"windows-1253", None))
        self.open_format.setItemText(12, QCoreApplication.translate("gui", u"windows-1254", None))
        self.open_format.setItemText(13, QCoreApplication.translate("gui", u"windows-1255", None))
        self.open_format.setItemText(14, QCoreApplication.translate("gui", u"windows-1256", None))
        self.open_format.setItemText(15, QCoreApplication.translate("gui", u"windows-1257", None))
        self.open_format.setItemText(16, QCoreApplication.translate("gui", u"windows-1258", None))

        self.save_format.setItemText(0, QCoreApplication.translate("gui", u"utf-8", None))
        self.save_format.setItemText(1, QCoreApplication.translate("gui", u"utf-8-sig", None))
        self.save_format.setItemText(2, QCoreApplication.translate("gui", u"gb2312", None))
        self.save_format.setItemText(3, QCoreApplication.translate("gui", u"gbk", None))
        self.save_format.setItemText(4, QCoreApplication.translate("gui", u"gb18030", None))
        self.save_format.setItemText(5, QCoreApplication.translate("gui", u"big5", None))
        self.save_format.setItemText(6, QCoreApplication.translate("gui", u"koi8-r", None))
        self.save_format.setItemText(7, QCoreApplication.translate("gui", u"cp932", None))
        self.save_format.setItemText(8, QCoreApplication.translate("gui", u"windows-1250", None))
        self.save_format.setItemText(9, QCoreApplication.translate("gui", u"windows-1251", None))
        self.save_format.setItemText(10, QCoreApplication.translate("gui", u"windows-1252", None))
        self.save_format.setItemText(11, QCoreApplication.translate("gui", u"windows-1253", None))
        self.save_format.setItemText(12, QCoreApplication.translate("gui", u"windows-1254", None))
        self.save_format.setItemText(13, QCoreApplication.translate("gui", u"windows-1255", None))
        self.save_format.setItemText(14, QCoreApplication.translate("gui", u"windows-1256", None))
        self.save_format.setItemText(15, QCoreApplication.translate("gui", u"windows-1257", None))
        self.save_format.setItemText(16, QCoreApplication.translate("gui", u"windows-1258", None))

        self.title_label.setText(QCoreApplication.translate("gui", u"\u795e\u9f99\u52a0\u5bc6 v1.4", None))
        self.name_label.setText(QCoreApplication.translate("gui", u"by abcdesteve", None))
        self.unlock_bottom.setText(QCoreApplication.translate("gui", u"\u89e3\u5bc6", None))
        self.lock_bottom.setText(QCoreApplication.translate("gui", u"\u52a0\u5bc6", None))
    # retranslateUi

